spring:
  datasource:
    # 动态数据源配置
    dynamic:
      # 指定默认数据源名称
      primary: master
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
---

spring:
  redis:
    host: redisdev.project.qimiaowa.com
    port: 31379
    password: 1Qaz2wsx
    timeout: 10000
    jedis:
      maxActive: 600
      maxIdle: 10
      minIdle: 4
      maxWait: 3000
      testOnBorrow: true
      blockWhenExhausted: true
      testOnReturn: true
      testWhileIdle: true
      lifo: true
      timeBetweenEvictionRunsMillis: 30000
      numTestsPerEvictionRun: 60000
      minEvictableIdleTimeMillis: 60000
      pool:
        max-active: 600
        max-idle: 10
        min-idle: 4
        max-wait: 3000
    database: 6
---
server:
  port: 8088
mybatis:
  mapper-locations: /mapper/*.xml