spring:
  profiles:
    active: native
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /yxt
service:
  name: yxt